"""empty message

Revision ID: 953a56d69386
Revises: 8f1a388be306
Create Date: 2022-09-09 13:33:54.149202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "953a56d69386"
down_revision = "8f1a388be306"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column("user", "nit", existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "nit", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
